/// Flutter icons PocketWardrobe
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class PocketWardrobe {
  PocketWardrobe._();

  static const _kFontFam = 'PocketWardrobe';
  static const String? _kFontPkg = null;

  static const IconData shoe =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
